### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by mhalano** [Stebalien/localtime#2]
Should have "debian/" directory with instructions to build a .deb package.

**Comment by Stebalien** [comment]
I'm generally not a fan of bundling distro-specific packaging files but I guess Debian-based systems are common enough to warrant this. However, one of the reasons I don't use Debian is that I hate creating Debian packages so someone else will have to create it.

**Comment by evaryont** [comment]
If someone were too lazy to do it the "proper" way using Debian's own tools, there is also [fpm](https://github.com/jordansissel/fpm)

**Comment by domenkozar** [comment]
FYI: I've packaged it for https://github.com/NixOS/nixpkgs

**Comment by Stebalien** [comment]
@domenkozar awesome! Thanks.
