### ISSUE TITLE
Handle GeoClue restarts

### ISSUE THREAD

**Issue by Stebalien** [Stebalien/localtime#3]
Currently, we don't handle geoclue restarts. This means that if geoclue stops and then starts, we simply stop receiving location updates. This isn't too hard to fix, I'm just not very motivated.

**Comment by domenkozar** [comment]
Should be very easily fixable by doing `PartOf` as described in https://www.freedesktop.org/software/systemd/man/systemd.unit.html

**Comment by Stebalien** [comment]
Ah. Good point. My plan was to handle them in go (wait for the service to show up and then bring everything back up) but that's simpler. Fixed.
