### ISSUE TITLE
[Question] What triggers the daemon?

### ISSUE THREAD

**Issue by cagprado** [Stebalien/localtime#4]
Hi =)… It’s probably not the best approach to make a question in the Issues tracker but I really just wanted to understand what triggers the daemon to update the timezone?

For instance… when I start the daemon (assuming I’m connected) it will update the timezone… now, let’s say I change it by hand to another zone. What events would trigger (if any) the daemon to fix the timezone again, after that?

Best regards!

**Comment by Stebalien** [comment]
> It’s probably not the best approach to make a question in the Issues tracker

It's the only way at the moment so it's the "best" by definition. 🙂

To answer your question, I update the timezone whenever geoclue sends me a `LocationUpdated` event. However, I don't know how often it does that.
