### ISSUE TITLE
Allow running command after timezone change

### ISSUE THREAD

**Issue by domenkozar** [Stebalien/localtime#5]
Due to https://github.com/i3/i3status/issues/223 i3wm.org doesn't update the time, a possible workaround would be to execute `i3-msg restart` after timezone has changed.

**Comment by Stebalien** [comment]
So, it looks like that is now resolved. Is this still an issue? IMO, this really *shouldn't* be fixed here. Two possible solutions:

1. Listen for changes to the `/etc/localetime` symlink (e.g., with inotifywatch).
2. Listen for a change event (for the timezone) from systemd timedated (assuming it emits them, I'm not sure it does).

**Comment by domenkozar** [comment]
Agreed.
