### ISSUE TITLE
geoclue config?

### ISSUE THREAD

**Issue by cyrinux** [Stebalien/localtime#6]
Hi @Stebalien 

Thanks for this projects.

I try to get it working on a updated archlinux
I have error like this:
```
Aug 01 16:02:45 delluxe localtimed[27314]: Failed to start GeoClue2 Client: 'localtimed' disallowed, no agent for UID 62714
Aug 01 16:02:45 delluxe systemd[1]: localtime.service: Main process exited, code=exited, status=1/FAILURE
Aug 01 16:02:45 delluxe systemd[1]: localtime.service: Failed with result 'exit-code'.
```

Is there someting to do like for redshift https://github.com/jonls/redshift/issues/158#issuecomment-153847465 ?

Thanks

**Comment by Stebalien** [comment]
The correct fix is to (a) ship a desktop file and (b) *register* a custom "agent". This is stupid.

From a security standpoint, this is useless (as with most of GNOME's "security" endeavors) as Linux enforces security on a per-user basis. It looks like they eventually want more enforceable restrictions but starting out with unenforceable restrictions that break applications is just plain dumb.

**Comment by Stebalien** [comment]
Actually, it looks like registering a custom agent won't cut it. We have to convince the geoclue devs to whitelist the app.

**Comment by cyrinux** [comment]
Thanks @Stebalien is there a hope for this ?

**Comment by Stebalien** [comment]
I'm filing bugs.

**Comment by michaelpj** [comment]
Hi, I did a bit of looking into this for NixOS. It looks like it's on the distro or DE to make sure that there's an agent running (e.g. the demo agent).

However, there's still one annoyance, which is that the agent only works for the user it is run as. So either we'd need to start another agent for the localtime user, which is a pain, or localtime could be run as a user service. I tried the latter a little, but my initial hacking was not enough to make it work.

**Comment by michaelpj** [comment]
Actually, I don't think we could run an agent for the localtime user, because it needs to send the user a prompt to ask for permissions. (As far as I understand it, which is not very far :( )

**Comment by Stebalien** [comment]
> Actually, I don't think we could run an agent for the localtime user, because it needs to send the user a prompt to ask for permissions. (As far as I understand it, which is not very far :( )

Exactly. The problem here is that this is running as a system service. Geoclue provides a way to do this but it requires adding a line to the config file. I'm asking for a policykit style config drop-in system but it's not going well.

https://gitlab.freedesktop.org/geoclue/geoclue/issues/74

**Comment by michaelpj** [comment]
How feasible is making a user service? I experimented with whitelisting the application, but that doesn't seem to help since it still seems to want an agent for the UID.

**Comment by Stebalien** [comment]
I could do that but:

1. The user would need to be allowed to set the timezone (see https://github.com/Stebalien/localtime/blob/master/polkit.rules.in).
2. It really doesn't make sense to run this on a per-user basis. It's a system daemon and affects the system as a whole (by setting the timezone).

---

So,  I *may* be able to do one of:

1. Launch the demo agent in a subprocess.
2. Masquerade as the demo agent (again, there's no actual security here).

**Comment by michaelpj** [comment]
Yes, you're right. It's a bit annoying that afaict whitelisting the application in `geoclue.conf` doesn't prevent you from needing an agent. I opened https://gitlab.freedesktop.org/geoclue/geoclue/issues/76 for that - I think that *should* be allowed, and then I think we'd be okay so long as we supply a valid `.desktop` file (because reasons).

**Comment by cyrinux** [comment]
Hi guys,
Any news on the issue? I understand in https://gitlab.freedesktop.org/geoclue/geoclue/issues/76 that we will be whitelisted? Is-it?

**Comment by Stebalien** [comment]
It has not been whitelisted and I'm not sure if this app is popular enough to make the cut. Really, the next steps are:

1. For now, add an "install" file to this package that edits the config.
2. Submit a PR to allow drop-in configs in geoclue.

**Comment by halocaridina** [comment]
Is this still an issue or has it been resolved as in https://gitlab.freedesktop.org/geoclue/geoclue/issues/76? 

Thanks for the update and the project!!

**Comment by Stebalien** [comment]
This has not been resolved as this app still hasn't been whitelisted by default.
