### ISSUE TITLE
Failed to connect to system bus

### ISSUE THREAD

**Issue by ckotte** [Stebalien/localtime#9]
I'm running Arch Linux and I just discovered localtime doesn't work anymore:

```
May 30 01:35:59 icarus systemd[1]: Started Timezone Updater Daemon.
May 30 01:35:59 icarus localtimed[6431]: 2022/05/30 01:35:59 Failed to connect to system bus: read unix @->/run/dbus/system_bus_socket: recvmsg: connection reset by peer
May 30 01:35:59 icarus systemd[1]: localtime.service: Main process exited, code=exited, status=1/FAILURE
May 30 01:35:59 icarus systemd[1]: localtime.service: Failed with result 'exit-code'.
...
Jun 11 00:39:21 icarus systemd[1]: Started Timezone Updater Daemon.
Jun 11 00:39:21 icarus localtimed[68266]: 2022/06/11 00:39:21 Failed to connect to system bus: read unix @->/run/dbus/system_bus_socket: recvmsg: connection reset by peer
Jun 11 00:39:21 icarus systemd[1]: localtime.service: Main process exited, code=exited, status=1/FAILURE
Jun 11 00:39:21 icarus systemd[1]: localtime.service: Failed with result 'exit-code'.
```

Any idea why it cannot access the system bus anymore?

**Comment by sudoforge** [comment]
@ckotte did you ever figure this out? i'm just noticing that it's been failing for me, too. i haven't dug into why this might be happening, though, so this is really just a flyby comment hoping you can save me some debugging time :)

**Comment by Stebalien** [comment]
I'm not sure why you might be failing to connect to the system bus unless there's some kind of sandboxing issue. However, I have had problems with geoclue2's permissions to the point where I just flat out gave up.

**Comment by EvyBongers** [comment]
I just noticed this issue myself. The problem seems to be related to the `DynamicUser` directive.
When I add a system user (`sudo useradd --system localtimed`) and remove the `DynamicUser` directive from the service file, the service seems to work fine.

**Comment by nogweii** [comment]
Indeed, adding a drop-in file at `/etc/systemd/system/localtime.service.d/static-user.conf` resolves the error:

```ini
[Service]
DynamicUser=false
User=localtimed
```

Along with the file `/etc/sysusers.d/localtimed.conf` to make the dedicated user:

```
u localtimed - "Local time daemon" - -
```

While that resolves the system bus error, it doesn't seem like enough. I then get this error message:

```
Dec 25 20:58:07 localhost.lan localtimed[63011]: 2023/12/26 03:58:07 Failed to initialize GeoClue2 Client: Message recipient disconnected from message bus without replying
```

**Comment by EvyBongers** [comment]
@Stebalien I patched the AUR package locally and have gotten it to work (nicely?) with Geoclue. 
```
$ systemctl status localtime.service
● localtime.service - Timezone Updater Daemon
     Loaded: loaded (/etc/systemd/system/localtime.service; enabled; preset: disabled)
     Active: active (running) since Sat 2023-12-30 23:05:04 CET; 9min ago
   Main PID: 13539 (localtimed)
      Tasks: 6 (limit: 16579)
     Memory: 7.4M (peak: 7.7M)
        CPU: 93ms
     CGroup: /system.slice/localtime.service
             └─13539 /usr/bin/localtimed

Dec 30 23:05:04 laptop systemd[1]: Started Timezone Updater Daemon.
Dec 30 23:05:06 laptop localtimed[13539]: 2023/12/30 23:05:06 Updated timezone to: Europe/Amsterdam
```

Would you be open to a PR with the changes I have? Alternatively, I can email you the diff for the `localtime-git` AUR package.

The changes include:
* Patching `localtime.service.in` to not use a dynamic user
* Adding a `sysusers.d` config file
* Adding a Geoclue demo agent service unit (which I think you used to ship at some point)

**Comment by Stebalien** [comment]
Please do submit a PR. I've never really gotten geoclue to work properly after they broke everything a few years ago (lots of pushback from upstream to the point where I mostly gave up on the project). But if you've managed to get it all working, I'm happy to review a PR.
